# 左右影像路徑
left_path: "images/left.jpg"
right_path: "images/right.jpg"

# 視差計算參數
num_disparities: 176    # 必須是16的倍數
block_size: 11

# 生成遮罩閾值與形態學參數
disparity_threshold: 35
morph_kernel_size: 5

# Dolly zoom 動畫參數
num_frames: 60          # 幀數，越多越順
max_bg_scale: 1.5       # 背景最大縮放比（>1）
fps: 30                 # 影片幀率
output_video: "result/dolly_zoom.mp4"
